# Generated by Django 3.1.5 on 2021-02-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('0', 'Uncategorized/Misc'), ('1', 'Produce'), ('2', 'Meat'), ('3', 'Seafood'), ('4', 'Beverages'), ('5', 'Deli'), ('6', 'Frozen')], default='0', max_length=2),
        ),
    ]
