# Generated by Django 3.1.5 on 2021-02-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20210216_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('1', 'Produce'), ('2', 'Meat'), ('3', 'Seafood'), ('4', 'Beverages'), ('5', 'Deli'), ('0', 'Uncategorized/Misc')], default='0', max_length=2),
        ),
    ]
