# Generated by Django 3.1.5 on 2021-02-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210216_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('AM', 'Art & Music'), ('BI', 'Biographies'), ('BU', 'Business'), ('CO', 'Comics'), ('CT', 'Computers & Tech'), ('CK', 'Cooking'), ('ER', 'Education & Reference'), ('EN', 'Entertainment'), ('LQ', 'LGBTQ'), ('HF', 'Health & Fitness'), ('HI', 'History'), ('HC', 'Hobbies & Crafts'), ('HG', 'Home & Garden'), ('HO', 'Horror'), ('KI', 'Kids'), ('LF', 'Literature & Fiction'), ('ME', 'Medical'), ('MY', 'Mysteries'), ('PA', 'Parenting'), ('RE', 'Religion'), ('RO', 'Romance'), ('SF', 'Sci-Fi & Fantasy'), ('SM', 'Science & Math'), ('SH', 'Self-Help'), ('SS', 'Social Sciences'), ('SP', 'Sports'), ('TE', 'Teen'), ('TR', 'Travel'), ('TC', 'True Crime'), ('UM', 'Uncategorized & Misc'), ('WE', 'Westerns')], default='UM', max_length=2),
        ),
    ]
